import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { usePack } from "../store/usePack";
import ListingCard from "./ListingCard";
export default function Snapshot() {
    const analysis = usePack((s) => s.analysis);
    return (_jsxs("div", { className: "space-y-4", children: [_jsx(ListingCard, {}), !analysis ? (_jsxs("p", { className: "text-sm opacity-70", children: ["Click ", _jsx("b", { children: "Analyze" }), " to generate a snapshot of issues, hidden costs, and key dates."] })) : (_jsxs(_Fragment, { children: [_jsxs("div", { className: "grid sm:grid-cols-2 gap-3", children: [_jsxs("div", { className: "card", children: [_jsx("div", { className: "text-sm opacity-70", children: "Verdict" }), _jsx("div", { className: "text-lg font-semibold", children: analysis.verdict })] }), _jsxs("div", { className: "card", children: [_jsx("div", { className: "text-sm opacity-70", children: "Hidden Cost (est.)" }), _jsxs("div", { className: "text-lg font-semibold", children: ["\u00A3", analysis.hiddenCostTotal.toLocaleString()] })] }), _jsxs("div", { className: "card", children: [_jsx("div", { className: "text-sm opacity-70", children: "Auction" }), _jsx("div", { children: analysis.keyDates.auction })] }), _jsxs("div", { className: "card", children: [_jsx("div", { className: "text-sm opacity-70", children: "Completion" }), _jsx("div", { children: analysis.keyDates.completion ?? "—" })] })] }), _jsxs("div", { className: "card", children: [_jsx("h3", { className: "font-semibold mb-2", children: "Top 5 Issues" }), _jsx("ul", { className: "space-y-2", children: analysis.topIssues.map((i) => (_jsxs("li", { className: "flex items-start gap-2", children: [_jsx("span", { className: `mt-1 h-2 w-2 rounded-full ${i.severity === "red"
                                                ? "bg-red-500"
                                                : i.severity === "amber"
                                                    ? "bg-amber-500"
                                                    : "bg-emerald-500"}` }), _jsxs("div", { children: [_jsx("div", { className: "font-medium", children: i.title }), i.note && _jsx("div", { className: "text-xs opacity-70", children: i.note }), typeof i.estCost === "number" && (_jsxs("div", { className: "text-xs", children: ["Est. \u00A3", i.estCost.toLocaleString()] }))] })] }, i.id))) })] })] }))] }));
}
